---
authors: [ "Geoffrey Hunter" ]
categories: [ "Programming", "Cloud", "AWS" ]
date: 2021-08-26
description: "An introduction to AWS IoT."
draft: false
lastmod: 2021-08-26
tags: [ "programming", "cloud", "AWS", "Amazon Web Services", "IoT" ]
title: "AWS IoT"
type: "page"
---

WARNING: This page is in notes format, and may not be of the same quality as other pages on this site.

== What Is A Device Shadow?

AWS introduces the concept of a _device shadow_ A device shadow is a virtual, persistent copy of a embedded devices state which is stored in the cloud. The device shadow can be interacted with from IoT Core whether or not the actual device is connected or not. The devices shadow is represented as a JSON document. You can think of the device shadow as a cache of the device state which prevents the disruption of missed communications when the actual device goes temporarily offline, usually due to unstable internet connectivity (other services can still read/write to the shadowed device state). The actual device, when online, can get/update/delete it's latest state as well as receive notifications when the state changes.

== AWS Jobs

Jobs can be sent to devices using any of the following three protocols:

* MQTT
* HTTP
* HTTP TLS

== AWS IoT Device SDK For Embedded C (C-SDK)

The AWS IoT Device SDK For Embedded C (commonly shortened to C-SDK) that you can use/run on embedded devices to turn them into AWS IoT nodes that can connect to the AWS IoT Core. It is written in standard C and contains the following components:

* coreMQTT
* coreHTTP
* coreJSON
* corePKCS11
* AWS IoT Device Shadow
* AWS IoT Jobs
* AWS IoT Device Defender
* AWS IoT Over-the-air Update
* AWS IoT Fleet Provisioning
* AWS SigV4
* backoffAlgorithm

Most of these components have no dependencies other than the standard C library.

Link: https://github.com/aws/aws-iot-device-sdk-embedded-c

