// Pre-defined CRC algorithm catalogue. Ported from NinjaCalc
// (`utils/crc/crc-catalogue.js`). Each entry is consumable by `CrcGeneric`
// in `crc.js`. Polynomial / starting / xor-out / check values are written as
// numeric BigInt literals — JavaScript's `0xNN` is fine for ≤ 53-bit values,
// and we use `Number` for everything except the 64-bit entries (where we use
// BigInt literals directly).

export const CRC_ALGORITHMS = [
  { id: 'CRC_3_ROHC',           name: 'CRC-3/ROHC',                    crcWidthBits:  3, crcPolynomial: 0x3n,                  startingValue: 0x7n,                  reflectData: true,  reflectRemainder: true,  finalXorValue: 0x0n,                  checkValue: 0x6n },
  { id: 'CRC_4_INTERLAKEN',     name: 'CRC-4/INTERLAKEN',              crcWidthBits:  4, crcPolynomial: 0x3n,                  startingValue: 0xFn,                  reflectData: false, reflectRemainder: false, finalXorValue: 0xFn,                  checkValue: 0xBn },
  { id: 'CRC_4_ITU',            name: 'CRC-4/ITU',                     crcWidthBits:  4, crcPolynomial: 0x3n,                  startingValue: 0x0n,                  reflectData: true,  reflectRemainder: true,  finalXorValue: 0x0n,                  checkValue: 0x7n },
  { id: 'CRC_5_EPC',            name: 'CRC-5/EPC',                     crcWidthBits:  5, crcPolynomial: 0x09n,                 startingValue: 0x09n,                 reflectData: false, reflectRemainder: false, finalXorValue: 0x00n,                 checkValue: 0x00n },
  { id: 'CRC_5_ITU',            name: 'CRC-5/ITU',                     crcWidthBits:  5, crcPolynomial: 0x15n,                 startingValue: 0x00n,                 reflectData: true,  reflectRemainder: true,  finalXorValue: 0x00n,                 checkValue: 0x07n },
  { id: 'CRC_5_USB',            name: 'CRC-5/USB',                     crcWidthBits:  5, crcPolynomial: 0x05n,                 startingValue: 0x1Fn,                 reflectData: true,  reflectRemainder: true,  finalXorValue: 0x1Fn,                 checkValue: 0x19n },
  { id: 'CRC_6_CDMA2000_A',     name: 'CRC-6/CDMA2000-A',              crcWidthBits:  6, crcPolynomial: 0x27n,                 startingValue: 0x3Fn,                 reflectData: false, reflectRemainder: false, finalXorValue: 0x00n,                 checkValue: 0x0Dn },
  { id: 'CRC_6_CDMA2000_B',     name: 'CRC-6/CDMA2000-B',              crcWidthBits:  6, crcPolynomial: 0x07n,                 startingValue: 0x3Fn,                 reflectData: false, reflectRemainder: false, finalXorValue: 0x00n,                 checkValue: 0x3Bn },
  { id: 'CRC_6_DARC',           name: 'CRC-6/DARC',                    crcWidthBits:  6, crcPolynomial: 0x19n,                 startingValue: 0x00n,                 reflectData: true,  reflectRemainder: true,  finalXorValue: 0x00n,                 checkValue: 0x26n },
  { id: 'CRC_6_ITU',            name: 'CRC-6/ITU',                     crcWidthBits:  6, crcPolynomial: 0x03n,                 startingValue: 0x00n,                 reflectData: true,  reflectRemainder: true,  finalXorValue: 0x00n,                 checkValue: 0x06n },
  { id: 'CRC_7',                name: 'CRC-7',                         crcWidthBits:  7, crcPolynomial: 0x09n,                 startingValue: 0x00n,                 reflectData: false, reflectRemainder: false, finalXorValue: 0x00n,                 checkValue: 0x75n },
  { id: 'CRC_7_ROHC',           name: 'CRC-7/ROHC',                    crcWidthBits:  7, crcPolynomial: 0x4Fn,                 startingValue: 0x7Fn,                 reflectData: true,  reflectRemainder: true,  finalXorValue: 0x00n,                 checkValue: 0x53n },
  { id: 'CRC_7_UMTS',           name: 'CRC-7/UMTS',                    crcWidthBits:  7, crcPolynomial: 0x45n,                 startingValue: 0x00n,                 reflectData: false, reflectRemainder: false, finalXorValue: 0x00n,                 checkValue: 0x61n },
  { id: 'CRC_8_CDMA2000',       name: 'CRC-8/CDMA2000',                crcWidthBits:  8, crcPolynomial: 0x9Bn,                 startingValue: 0xFFn,                 reflectData: false, reflectRemainder: false, finalXorValue: 0x00n,                 checkValue: 0xDAn },
  { id: 'CRC_8_DARC',           name: 'CRC-8/DARC',                    crcWidthBits:  8, crcPolynomial: 0x39n,                 startingValue: 0x00n,                 reflectData: true,  reflectRemainder: true,  finalXorValue: 0x00n,                 checkValue: 0x15n },
  { id: 'CRC_8_EBU',            name: 'CRC-8/EBU, CRC-8/AES',          crcWidthBits:  8, crcPolynomial: 0x1Dn,                 startingValue: 0xFFn,                 reflectData: true,  reflectRemainder: true,  finalXorValue: 0x00n,                 checkValue: 0x97n },
  { id: 'CRC_8_I_CODE',         name: 'CRC-8/I-CODE',                  crcWidthBits:  8, crcPolynomial: 0x1Dn,                 startingValue: 0xFDn,                 reflectData: false, reflectRemainder: false, finalXorValue: 0x00n,                 checkValue: 0x7En },
  { id: 'CRC_8_ITU_ATM_HEC',    name: 'CRC-8/ITU, ATM HEC',            crcWidthBits:  8, crcPolynomial: 0x07n,                 startingValue: 0x00n,                 reflectData: false, reflectRemainder: false, finalXorValue: 0x55n,                 checkValue: 0xA1n },
  { id: 'CRC_8_LTE',            name: 'CRC-8/LTE',                     crcWidthBits:  8, crcPolynomial: 0x9Bn,                 startingValue: 0x00n,                 reflectData: false, reflectRemainder: false, finalXorValue: 0x00n,                 checkValue: 0xEAn },
  { id: 'CRC_8_MAXIM',          name: 'CRC-8/MAXIM',                   crcWidthBits:  8, crcPolynomial: 0x31n,                 startingValue: 0x00n,                 reflectData: true,  reflectRemainder: true,  finalXorValue: 0x00n,                 checkValue: 0xA1n },
  { id: 'CRC_8_SAE_J1850',      name: 'CRC-8/SAE-J1850',               crcWidthBits:  8, crcPolynomial: 0x1Dn,                 startingValue: 0xFFn,                 reflectData: false, reflectRemainder: false, finalXorValue: 0xFFn,                 checkValue: 0x4Bn },
  { id: 'CRC_8_SMBUS',          name: 'CRC-8/SMBus',                   crcWidthBits:  8, crcPolynomial: 0x07n,                 startingValue: 0x00n,                 reflectData: false, reflectRemainder: false, finalXorValue: 0x00n,                 checkValue: 0xF4n },
  { id: 'CRC_8_WCDMA',          name: 'CRC-8/WCDMA',                   crcWidthBits:  8, crcPolynomial: 0x9Bn,                 startingValue: 0x00n,                 reflectData: true,  reflectRemainder: true,  finalXorValue: 0x00n,                 checkValue: 0x25n },
  { id: 'CRC_10',               name: 'CRC-10',                        crcWidthBits: 10, crcPolynomial: 0x233n,                startingValue: 0x000n,                reflectData: false, reflectRemainder: false, finalXorValue: 0x000n,                checkValue: 0x199n },
  { id: 'CRC_15_CAN2',          name: 'CRC-15, CAN2.0',                crcWidthBits: 15, crcPolynomial: 0x4599n,               startingValue: 0x0000n,               reflectData: false, reflectRemainder: false, finalXorValue: 0x0000n,               checkValue: 0x059En },
  { id: 'CRC_16_ARC_IBM',       name: 'CRC-16/IBM/ARC/LHA',            crcWidthBits: 16, crcPolynomial: 0x8005n,               startingValue: 0x0000n,               reflectData: true,  reflectRemainder: true,  finalXorValue: 0x0000n,               checkValue: 0xBB3Dn },
  { id: 'CRC_16_CCITT_FALSE',   name: 'CRC-16/CCITT-FALSE',            crcWidthBits: 16, crcPolynomial: 0x1021n,               startingValue: 0xFFFFn,               reflectData: false, reflectRemainder: false, finalXorValue: 0x0000n,               checkValue: 0x29B1n },
  { id: 'CRC_16_CDMA2000',      name: 'CRC-16/CDMA-2000',              crcWidthBits: 16, crcPolynomial: 0xC867n,               startingValue: 0xFFFFn,               reflectData: false, reflectRemainder: false, finalXorValue: 0x0000n,               checkValue: 0x4C06n },
  { id: 'CRC_16_GENIBUS',       name: 'CRC-16/GENIBUS',                crcWidthBits: 16, crcPolynomial: 0x1021n,               startingValue: 0xFFFFn,               reflectData: false, reflectRemainder: false, finalXorValue: 0xFFFFn,               checkValue: 0xD64En },
  { id: 'CRC_16_KERMIT',        name: 'CRC-16/KERMIT/CCITT-TRUE',      crcWidthBits: 16, crcPolynomial: 0x1021n,               startingValue: 0x0000n,               reflectData: true,  reflectRemainder: true,  finalXorValue: 0x0000n,               checkValue: 0x2189n },
  { id: 'CRC_16_MAXIM',         name: 'CRC-16/MAXIM',                  crcWidthBits: 16, crcPolynomial: 0x8005n,               startingValue: 0x0000n,               reflectData: true,  reflectRemainder: true,  finalXorValue: 0xFFFFn,               checkValue: 0x44C2n },
  { id: 'CRC_16_MODBUS',        name: 'CRC-16/MODBUS',                 crcWidthBits: 16, crcPolynomial: 0x8005n,               startingValue: 0xFFFFn,               reflectData: true,  reflectRemainder: true,  finalXorValue: 0x0000n,               checkValue: 0x4B37n },
  { id: 'CRC_16_X25',           name: 'CRC-16/X25/IBM-SLDC/ISO-HDLC',  crcWidthBits: 16, crcPolynomial: 0x1021n,               startingValue: 0xFFFFn,               reflectData: true,  reflectRemainder: true,  finalXorValue: 0xFFFFn,               checkValue: 0x906En },
  { id: 'CRC_16_XMODEM',        name: 'CRC-16/XMODEM/ACORN/LTE',       crcWidthBits: 16, crcPolynomial: 0x1021n,               startingValue: 0x0000n,               reflectData: false, reflectRemainder: false, finalXorValue: 0x0000n,               checkValue: 0x31C3n },
  { id: 'CRC_24_OPEN_PGP',      name: 'CRC-24/OPENPGP',                crcWidthBits: 24, crcPolynomial: 0x864CFBn,             startingValue: 0xB704CEn,             reflectData: false, reflectRemainder: false, finalXorValue: 0x000000n,             checkValue: 0x21CF02n },
  { id: 'CRC_24_BLE',           name: 'CRC-24/BLE',                    crcWidthBits: 24, crcPolynomial: 0x00065Bn,             startingValue: 0x555555n,             reflectData: true,  reflectRemainder: true,  finalXorValue: 0x000000n,             checkValue: 0xC25A56n },
  { id: 'CRC_32_ADCCP_PKZIP',   name: 'CRC-32/ADCCP/PKZIP',            crcWidthBits: 32, crcPolynomial: 0x04C11DB7n,           startingValue: 0xFFFFFFFFn,           reflectData: true,  reflectRemainder: true,  finalXorValue: 0xFFFFFFFFn,           checkValue: 0xCBF43926n },
  { id: 'CRC_32_POSIX_CKSUM',   name: 'CRC-32/POSIX/CKSUM',            crcWidthBits: 32, crcPolynomial: 0x04C11DB7n,           startingValue: 0x00000000n,           reflectData: false, reflectRemainder: false, finalXorValue: 0xFFFFFFFFn,           checkValue: 0x765E7680n },
  { id: 'CRC_40_GSM',           name: 'CRC-40/GSM',                    crcWidthBits: 40, crcPolynomial: 0x0004820009n,         startingValue: 0x0000000000n,         reflectData: false, reflectRemainder: false, finalXorValue: 0xFFFFFFFFFFn,         checkValue: 0xD4164FC646n },
  { id: 'CRC_64',               name: 'CRC-64',                        crcWidthBits: 64, crcPolynomial: 0x42F0E1EBA9EA3693n,   startingValue: 0x0000000000000000n,   reflectData: false, reflectRemainder: false, finalXorValue: 0x0000000000000000n,   checkValue: 0x6C40DF5F0B497347n },
];

export function findAlgorithm(id) {
  return CRC_ALGORITHMS.find((a) => a.id === id);
}
