baseURL: 'https://blog.mbedded.ninja/'
languageCode: en-us
title: mbedded.ninja
sectionPagesMenu: main
pluralizelisttitles: 'false'
pygmentsCodeFences: 'true'
disqusShortname: blog-mbedded-ninja
#googleAnalytics: G-0WDEVQLPS2 # Used to be UA-92834105-2 (universal ID)
preserveTaxonomyNames: 'true'
enableGitInfo: false
timeout: 60000 # Used be to 30,000 but this would timeout on netlify
assetDir: assets
params:
  author: Geoffrey Hunter
  description: An embedded engineering site that's got your back.
  images:
    - /images/logo/mbedded-ninja-twitter-card-600x300.png
  # rssTypes lists the content types which will be included in the RSS feed
  # This is referenced in rss.xml
  rssTypes:
  - page
  - post
markup:
  tableOfContents:
    ordered: false
    startLevel: 2
    endLevel: 5 # Used to be 2 to keep the TOC short, but now we added separate scrolling for the right-hand column for the TOC
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true # Show line numbers in the left gutter of code blocks
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: rainbow_dash # monokai
    tabWidth: 4
  asciidocext:
    backend: html5
    workingfoldercurrent: false
    trace: true
    verbose: true
    attributes:
      includedir: include
      icons: image
      icontype: svg
      iconsdir: /assets/icons
      experimental: true
      source-highlighter: rouge
      rouge-css: style
      rouge-style: github
      # The TOC and the number of levels for AsciiDoc pages is determined below
      # rather than with the markup->tableOfContents section above.
      toc: true
      toclevels: 4
      xrefstyle: short
      stem: latexmath
      sectnums: true
related:
  threshold: 80
  includeNewer: true
  toLower: false
  indices:
    - name: keywords
      weight: 100
    - name: tags
      weight: 100
taxonomies:
  category: categories
  tag: tags
  author: "authors"
outputs:
  home:
    - HTML
    - RSS # Output RSS feed for entire blog at /index.xml
security:
  enableInlineShortcodes: false
  exec:
    allow:
    - ^dart-sass-embedded$
    - ^go$
    - ^npx$
    - ^postcss$
    - ^asciidoctor$ # Added by gbmhunter to allow asciidoctor. Not included by default!
    osEnv:
    - (?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|GEM_PATH)$
  funcs:
    getenv:
    - ^HUGO_
  http:
    methods:
    - (?i)GET|POST
    urls:
    - .*

services:
  rss:
    limit: 100 # Sets the max. number of RSS entries (most recent allowed through)
