baseURL: 'https://blog.mbedded.ninja/'
languageCode: en-us
title: mbedded.ninja
sectionPagesMenu: main
pluralizelisttitles: 'false'
pygmentsCodeFences: 'true'
disqusShortname: blog-mbedded-ninja
#googleAnalytics: G-0WDEVQLPS2 # Used to be UA-92834105-2 (universal ID)
preserveTaxonomyNames: 'true'
enableGitInfo: false
timeout: 60000 # Used be to 30,000 but this would timeout on netlify
assetDir: assets
enableRobotsTXT: true # Makes Hugo spit out a robots.txt file with the contents: User-agent: *
params:
  author: Geoffrey Hunter
  description: An embedded engineering site that's got your back.
  images:
    - /images/logo/mbedded-ninja-twitter-card-600x300.png
  # rssTypes lists the content types which will be included in the RSS feed
  # This is referenced in rss.xml
  rssTypes:
  - page
  - post
  math: true
markup:
  tableOfContents:
    ordered: false
    startLevel: 2
    endLevel: 4 # Used to be 2 to keep the TOC short, but now we added separate scrolling for the right-hand column for the TOC
  goldmark:
    renderer:
      unsafe: true
    extensions:
      passthrough:
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - \(
            - \)
        enable: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true # Show line numbers in the left gutter of code blocks
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: monokai # rainbow_dash
    tabWidth: 4
related:
  threshold: 80
  includeNewer: true
  toLower: false
  indices:
    # - name: keywords
    #   weight: 100
    - name: tags
      weight: 100
      cardinalityThreshold: 20 # Removes tags that are used in more than XX % of the pages
taxonomies:
  category: categories
  tag: tags
  author: "authors"
outputs:
  home:
    - HTML
    - RSS # Output RSS feed for entire blog at /index.xml
security:
  enableInlineShortcodes: false
  exec:
    allow:
    - ^dart-sass-embedded$
    - ^go$
    - ^npx$
    - ^postcss$
    osEnv:
    - (?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|GEM_PATH)$
  funcs:
    getenv:
    - ^HUGO_
  http:
    methods:
    - (?i)GET|POST
    urls:
    - .*

services:
  rss:
    limit: 100 # Sets the max. number of RSS entries (most recent allowed through)
