baseURL: 'https://blog.mbedded.ninja/'
languageCode: en-us
title: mbedded.ninja
sectionPagesMenu: main
pluralizelisttitles: 'false'
pygmentsCodeFences: 'true'
disqusShortname: blog-mbedded-ninja
#googleAnalytics: G-0WDEVQLPS2 # Used to be UA-92834105-2 (universal ID)
preserveTaxonomyNames: 'true'
enableGitInfo: false
timeout: 30000
assetDir: assets
params:
  author: Geoffrey Hunter
  description: An embedded engineering site that's got your back.
  images:
    - /images/logo/mbedded-ninja-twitter-card-600x300.png
markup:
  tableOfContents:
    ordered: false
    startLevel: 2
    endLevel: 5 # Used to be 2 to keep the TOC short, but now we added separate scrolling for the right-hand column for the TOC
  goldmark:
    renderer:
      unsafe: true
  asciidocext:
    backend: html5
    workingfoldercurrent: false
    trace: true
    verbose: true
    attributes:
      includedir: include
      icons: image
      icontype: svg
      iconsdir: /assets/icons
      experimental: true
      source-highlighter: rouge
      rouge-css: style
      rouge-style: github
      # The TOC and the number of levels for AsciiDoc pages is determined below
      # rather than with the markup->tableOfContents section above.
      toc: true
      toclevels: 4
      xrefstyle: short
      stem: latexmath
      sectnums: true
related:
  threshold: 80
  includeNewer: true
  toLower: false
  indices:
    - name: keywords
      weight: 100
    - name: tags
      weight: 100
taxonomies:
  category: categories
  tag: tags
  author: "authors"
outputs:
  home:
    - HTML
    - RSS
security:
  enableInlineShortcodes: false
  exec:
    allow:
    - ^dart-sass-embedded$
    - ^go$
    - ^npx$
    - ^postcss$
    - ^asciidoctor$ # Added by gbmhunter to allow asciidoctor. Not included by default!
    osEnv:
    - (?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$
  funcs:
    getenv:
    - ^HUGO_
  http:
    methods:
    - (?i)GET|POST
    urls:
    - .*