#############################  Display  #############################

# Path to summary output file.
output = "report1.md"

format = "Markdown"

#############################  Cache  ###############################

# Enable link caching. This can be helpful to avoid checking the same links on
# multiple runs.
cache = true

# Discard all cached requests older than this duration.
max_cache_age = "2d"

#############################  Runtime  #############################

# Maximum number of concurrent link checks.
max_concurrency = 10

#############################  Requests  ############################

include = ['.*localhost.*']

exclude = ['.*']

include_fragments = true

base = "http://localhost:1313/"
