[build]
publish = "public"
# We run the hugo build first, and then pagefind on hugo's output
# to generate the search data/javascript (this will also be added
# to the public directory)
command = "hugo --minify && npx -y pagefind@v1.0.4 --site public"

[context.production.environment]
HUGO_VERSION = "0.123.0"
HUGO_ENV = "production"