---
authors: [ "Geoffrey Hunter" ]
categories: [ "Programming", "Cloud", "AWS" ]
date: 2021-09-06
draft: false
lastmod: 2021-09-06
tags: [ "programming", "cloud", "AWS" ]
title: "Creating A Scheduled Lambda Function Using AWS CDK"
type: "page"
---

WARNING: This page is in notes format, and may not be of the same quality as other pages on this site.

== Overview

We will use Python in this example. Most of the example would be the same for a different language, however the dependency inclusion into the lambda is different for every language. This example shows how the CDK can automatically bundle Python lambda dependencies defined in a `requirements.txt`.

This tutorial assumes you are running Windows. However, most of the instructions are compatible with Linux, aside from some tweaks needed in this installation step.

== Installation Of Dependencies

Let's install the required development dependencies using `choco` (replace `choco` with `apt` or similar for Linux distros). This will have to be done with administrator privileges:

[source,shell]
----
choco install -y awscli nodejs docker-desktop python
----

Then install the AWS CDK using `npm`. AWS CDK provides the `cdk` command to perform CDK specific actions, and uses the AWS CLI (`aws` command) under the hood.

[source,shell]
----
npm install -g aws-cdk
----

== General Config

If you haven't done already, the AWS CLI (not the AWS CDK, but CLI) needs configuring:

[source,shell]
----
aws configure
----

Enter in your AWS key ID and secret when prompted (if you don't have one of these, create one via the AWS Web Console).

Now "bootstrap" the CDK. Bootstrapping creates some buckets in S3 that the CDK needs to deploy infrastructure. This step only needs to be done once:

[source,shell]
----
cdk bootstrap aws://<account ID>/<region>
----

The output should look something like this:

[source,shell]
----
 ⏳  Bootstrapping environment aws://<account ID>/<region>...
CDKToolkit: creating CloudFormation changeset...
  0/3 |2:20:54 pm | REVIEW_IN_PROGRESS   | AWS::CloudFormation::Stack | CDKToolkit User Initiated
  0/3 |2:20:59 pm | CREATE_IN_PROGRESS   | AWS::CloudFormation::Stack | CDKToolkit User Initiated
  0/3 |2:21:02 pm | CREATE_IN_PROGRESS   | AWS::S3::Bucket       | StagingBucket
  0/3 |2:21:06 pm | CREATE_IN_PROGRESS   | AWS::S3::Bucket       | StagingBucket Resource creation Initiated
  1/3 |2:21:27 pm | CREATE_COMPLETE      | AWS::S3::Bucket       | StagingBucket 
  1/3 |2:21:29 pm | CREATE_IN_PROGRESS   | AWS::S3::BucketPolicy | StagingBucketPolicy 
  1/3 |2:21:30 pm | CREATE_IN_PROGRESS   | AWS::S3::BucketPolicy | StagingBucketPolicy Resource creation Initiated
  2/3 |2:21:30 pm | CREATE_COMPLETE      | AWS::S3::BucketPolicy | StagingBucketPolicy 
  3/3 |2:21:31 pm | CREATE_COMPLETE      | AWS::CloudFormation::Stack | CDKToolkit
 ✅  Environment aws://<account ID>/<region> bootstrapped.
----

== Creating A New CDK Project

Let's create a new CDK project. Make a new directory called `cdk_example` (it can't have anything in it). We'll use python for this example, so we provide the flag `--language python`.

NOTE: The language specified here is not the language which the lambda runs, but the language used to describe the cloud infrastructure. Similarly with the dependencies, these are build time dependencies required to build/deploy the stack, but not the runtime dependencies. This is an important distinction to remember! We'll get to the runtime language and dependencies later (which we also used Python for in this example).

[source,shell]
----
cdk init --language python
.venv/Scripts/activate
pip install -r ./requirements.txt
----

Notice how it has automatically created a virtual environment for us, which we activate on Windows with `.venv/Scripts/activate` (on Linux, use `source .venv/bin/activate` instead). We then installed the requirements that `cdk init` automatically created in the `requirements.txt` file with `pip`.

`cdk init` automatically provides basic build-time dependencies, but we still have to define addition build-time dependencies for making a lambda (and indeed, a specific Python lambda). All of the AWS CDK pip libraries start with `aws_cdk`.

[source,shell]
----
pip install aws_cdk.aws_lambda
pip install aws_cdk.aws_lambda_python
----

Rather than just using `aws_lambda`, I'm using `aws_lambda_python`. This is a special library for lambda's which run in a Python environment, and provides extra functionality to bundle up all the dependencies required automatically. Without this you'd have to work out how to do that yourself, so I definitely recommend using this feature!

There is a folder called `cdk_example` inside your `cdk_example` root directory. Inside this is a `cdk_example_stack.py` file. This file describes your stack.

.The `cdk_example_stack.py` file.
[source,python]
----
from aws_cdk import core as cdk

from aws_cdk import (    
    aws_lambda as _lambda,
    aws_lambda_python,
)

class CdkExampleStack(cdk.Stack):

    def __init__(self, scope: cdk.Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        # The code that defines your stack goes here
        my_lambda = aws_lambda_python.PythonFunction(
            self,
            'LambdaHandler',         
            runtime=_lambda.Runtime.PYTHON_3_8,
            entry='./lambda/',
            index='main.py',
            handler='handler',
        )
----
