---
authors: [ "Geoffrey Hunter" ]
date: 2013-04-08
draft: false
lastmod: 2021-08-24
tags: [ "electronics", "communication protocols", "ethernet", "internet", "IP" ]
title: "Ethernet Protocol"
type: "page"
---

WARNING: This page is in notes format, and may not be of the same quality as other pages on this site.

== Overview

== History

Originally, ethernet used a single coax cable (10base2).

== Components

=== Magnetics

Ethernet

=== Physical Layer (PHY)

The _PHY_ is the circuitry which drives the magnetics.

=== MAC

== Standards

=== 10BASE-T

Used Cat 3 cable/

=== 10BASE-T1L

Designed for automotive and IoT applications.

=== 10BASE-T1S

Designed for automotive and IoT applications. Allows for a multidrop architecture.

## Ethernet Jacks

Some ethernet jacks come with the magnetics already in-built, saving you the trouble of including them yourself on the mounted-to PCB

## Popular Chips

The W5200 WIZnet. The single chip implements the PHY, the TCP/IP stack (fully hardwired), and the 10/100 MAC Ethernet MAC, in a QFN-48 package. It uses the link:/electronics/communication-protocols/spi-communication-protocol/[SPI Protocol] to talk to a microcontroller. It's power save features include power-down mode and WOL (wake on LAN). It runs of 3.3V but has 5V I/O tolerance.

Microchips LAN8670, LAN8671 and LAN8672 are ethernet PHY ICs that use 10BASE-T1S, allowing a multidrop architecture of "at least 8 nodes and a minimum 25m of length".
